services:
  kaggle:
    build: .
    volumes:
      - $PWD:/kaggle/working
      - ./.jupyter:/root/.jupyter
      - ./.cache:/root/.cache
    working_dir: /kaggle/working
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTERLAB_SETTINGS_DIR=/kaggle/working/.jupyter-settings # jupyterの設定(保存用)
    ports:
      - 8889:8889
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --no-browser --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    shm_size: '64gb'

  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
