# MLFlow

mlflow:
    _target_: pytorch_lightning.loggers.MLFlowLogger
    experiment_name: ${experiment_name}
    tags:
        stage: train
    tracking_uri: "file:${work_dir}/mlruns"

# _target_: pytorch_lightning.loggers.MLFlowLogger

# experiment_name: ${experiment_name}
# tracking_uri: file://${work_dir}/mlruns
# tags:
# save_dir: ./mlruns
# prefix: ''
# artifact_location: